remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: [Analysis of Recipes and Ratings]
description: [This project investigates question related to cook time in a dataframe of recipes and ratings]
